const NewRemoteOptions = [
    'Choose a remote',
    'Fichier',
    'Akamai NetStorage',
    'Alias for an existing remote',
    'Amazon Drive',
    'S3',
    'Backblaze B',
    'Better checksums for other remotes',
    'Box',
    'Cache a remote',
    'Citrix Sharefile',
    'Combine several remotes into one',
    'Compress a remote',
    'Dropbox',
    'EncryptDecrypt a remote',
    'Enterprise File Fabric',
    'FTP',
    'Google Cloud Storage',
    'Google Drive',
    'Google Photos',
    'HTTP',
    'Hadoop distributed file system',
    'HiDrive',
    'In memory object storage system.',
    'Internet Archive',
    'Jottacloud',
    'Koofr or compatible storage providers',
    'Local Disk',
    'Mail.ru Cloud',
    'Mega',
    'Microsoft Azure Blob Storage',
    'Microsoft OneDrive',
    'OpenDrive',
    'OpenStack Swift',
    'Oracle Cloud Infrastructure Object Storage',
    'Pcloud',
    'Put.io',
    'QingCloud Object Storage',
    'SMB CIFS',
    'SSHSFTP',
    'Sia Decentralized Cloud',
    'Storj Decentralized Cloud Storage',
    'Sugarsync',
    'Transparently chunksplit large files',
    'Union merges the contents of several upstream fs',
    'Uptobox',
    'WebDAV',
    'Yandex Disk',
    'Zoho',
    'premiumize.me',
    'seafile'
];

export default NewRemoteOptions;
