name: make
on:
  [pull_request,push]
jobs:
  call-pytest:
    uses: QCDIS/rclone-data-mounter/.github/workflows/python-package-conda.yml@main
  call-build-wheel:
    uses: QCDIS/rclone-data-mounter/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-build-container:
    needs: call-build-wheel
    uses: QCDIS/rclone-data-mounter/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile
      tag: data-mounter
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}