name: make release
on:
  push:
    tags:
      - '*'

jobs:
  cleanup-artifacts:
    uses: QCDIS/NaaVRE/.github/workflows/artifacts-cleanup.yaml@main
  call-build-wheel:
    needs: cleanup-artifacts
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-save-in-relese:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/save-wheel-in-release.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: data-mounter-laserfarm
      push: true
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-multiply:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-MULTIPLY
      tag: data-mounter-multiply
      push: true
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-vol2bird
      tag: data-mounter-vol2bird
      push: true
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-pytorch:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: data-mounter-pytorch
      push: true
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}